stages:
  - lint
  - test

lint:
  stage: lint

  before_script:
    - apt-get update -qq && apt-get install -y -qq flake8
    - apt-get update -qq && apt-get install -y -qq pytest pytest-django

  script: flake8

test:
  stage: test

  script:
    - py.test