stages:
  - lint
  - test

lint:
  stage: lint

  before_script:
    - apt-get update -qq && apt-get install -y -qq flake8

  script: flake8

test:
  stage: test

  before_script:
    - export DJANGO_SETTINGS_MODULE=test_task.settings
    - apt-get update -qq && apt-get install -y -qq python3-pip
    - pip3 install pytest pytest-django --quiet

  script:
    - py.test