# Generated by Django 2.2.3 on 2019-07-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='weigth',
            new_name='weight',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='creation_time',
            field=models.FloatField(default=1562606960.84304, editable=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='update_time',
            field=models.FloatField(default=1562606960.843053),
        ),
    ]
