# Generated by Django 2.2.3 on 2019-07-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0005_auto_20190708_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='creation_time',
            field=models.FloatField(default=1563019170.616408, editable=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='update_time',
            field=models.FloatField(auto_created=True, default=1563019170.61642),
        ),
    ]
