# Generated by Django 2.2.3 on 2019-07-13 12:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0007_auto_20190713_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='appuser',
            name='creation_time',
            field=models.FloatField(default=1563020210.284373, editable=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='update_time',
            field=models.FloatField(default=1563020210.284385, editable=False),
        ),
        migrations.DeleteModel(
            name='tokens',
        ),
        migrations.AddField(
            model_name='token',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to='user_list.AppUser'),
        ),
    ]
