# Generated by Django 2.2.3 on 2019-07-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0010_auto_20190713_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
