# Generated by Django 2.2.3 on 2019-07-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0011_auto_20190713_1435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tokens',
            new_name='Token',
        ),
    ]
