# Generated by Django 2.2.3 on 2019-07-15 12:12

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0018_auto_20190715_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='creation_time',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='update_time',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True),
        ),
    ]
