# Generated by Django 2.2.3 on 2019-07-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0021_auto_20190715_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='food_preferences',
            field=models.CharField(choices=[('menu1', (('dish11', 'Dish11'), ('dish12', 'Dish12'))), ('menu2', (('dish21', 'Dish21'), ('dish22', 'Dish22'))), ('menu3', (('dish31', 'Dish31'), ('dish32', 'Dish32')))], default='menu1', max_length=32, null=True),
        ),
    ]
