# Generated by Django 2.2.3 on 2019-07-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0026_auto_20190718_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.TextField(max_length=32),
        ),
    ]
