# Generated by Django 2.2.3 on 2019-07-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0027_auto_20190719_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.TextField(max_length=32, unique=True),
        ),
    ]
