# Generated by Django 2.2.3 on 2019-07-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0029_auto_20190720_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='MyToken',
        ),
    ]
